[package]
name = "libbtrfsutil"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.0"
uuid = "0.8"
ffi = {package = "btrfsutil-sys", version = "1.2.1"}
